server:
  context-path: /srs-api
  port: 8081
  session:
    timeout: 900  # in seconds
    cookie:
      max-age: 900 # in seconds
    
#management:
#  port: 8083
#  security:
#    enabled: false

spring:
  main:
    web-environment: true
  mail:
    host: auohs-smtp.oracle.com
    username:
    password:
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
    test-connection: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.type: trace

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/SRS
    username: srs
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
    platform: mysql

  smaxDatasource:
    url: jdbc:oracle:thin:@auohsmaxi72-vip.oracleoutsourcing.com:11510/TMAX1O.ORACLEOUTSOURCING.COM
    username: FPALOU
    password: dev2@!8
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 30
  thymeleaf:
    enabled: false #disabled MVC
security:
  basic:
    enabled: true
#    Since we are using GMAIL, we have to use the same email address because GMAIL doesn't allow to change the FROM property
email:
  from: DE-SIE@de.pr.gov
website:
  url: https://localhost:3000
  context-path: /srs
logging:
  config: classpath:logback.xml

google:
  recaptcha:
    secret: 6Lffy0sUAAAAAJ5r6JXLUMuns1KnrQkWwzPFnDpZ
    active: false
oracle:
  proxy:
    host:
    port: 80

#move this to a different properties file
messages:
  user:
    min.age.validation: "Usuario debe tener 18 años o mas"


