server:
  context-path: @api.base.context-path@
  port: 8081
  session:
    timeout: @session.timeout@  # in seconds
    cookie:
      max-age: @cookie.max-age@ # in seconds
    
#management:
#  port: 8083
#  security:
#    enabled: false

srs:
  version: @srs.version@

spring:
  main:
    web-environment: true
  mail:
    host: @mail.host@
    port: @mail.port@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail.smtp.auth: @mail.smtp.auth@
      mail.smtp.starttls.enable: @mail.smtp.starttls.enable@
    test-connection: false
  jpa:
    hibernate:
      ddl-auto: @main.db.jpa.mode@
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.type: trace
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: @main.db.jdbc.url@
    username: @main.db.user@
    password: @main.db.password@
    driver-class-name: @main.db.driver.name@
    hikari:
      maximum-pool-size: 30
    platform: @main.db.platform@
  jmx:
    default-domain: @war.name@-${srs.version}
  smaxDatasource:
    url: @smax.db.jdbc.url@
    username: @smax.db.user@
    password: @smax.db.password@
    driver-class-name: @smax.db.driver.name@
    hikari:
      maximum-pool-size: 30

  thymeleaf:
    enabled: false #disabled MVC
security:
  basic:
    enabled: true
#    Since we are using GMAIL, we have to use the same email address because GMAIL doesn't allow to change the FROM property
email:
  from: @email.from@
website:
  url: @website.base.url@
  context-path: @website.base.context-path@
logging:
  config: classpath:logback.xml

property:
  load:
    test: Working


google:
  recaptcha:
    secret: @google.recaptcha.secret.key@
    active: @google.recaptcha.activate@
oracle:
  proxy:
    host: @oracle.proxy.host@
    port: @oracle.proxy.port@

smax:
  interface:
    use: @smax.interface.in-use@

#move this to a different properties file
messages:
  general:
    unknown.error: "Ha occurrido un error disculpe el incoveniente"
    missing.required.fields: "Faltan campos requeridos"
  fields:
      relationType: "Relación con el estudiante"
      firstName: "Nombre"
      middleName: "Segundo Nombre"
      lastName: "Apellidos"
      dateOfBirth: "Fecha de Nacimiento"
      studentNumber: "Número del SIE"
      ssn: "Seguro Social"
      gender: "Genero"
      lastSsn: "Ultimo 4 dígitos Seguro social"
      income: "Ingreso"
      totalFamilyMembers: "Total de miembros de la familia"
      physical.line1: "Dirección Residencial Linea 1"
      physical.city: "Dirección Residencial Ciudad"
      physical.zipcode: "Dirección Residencial Codigo postal"
      postal.line1: "Dirección Postal: Linea 1"
      postal.city: "Dirección Postal: Ciudad"
      postal.zipcode: "Dirección Postal: Codigo postal"
      language: "Lenguaje"
      citizenship: "Cuidadanía"
      ethnicCodes: "Debe selecciona al menos un codigo ethnico"

  search:
    student.missing.required.fields: "Debe proveer algunos de estos dos campos (Ultimo SSN o Numero Estudiante)"
  user:
    missing.required.fields: "Faltan campos requeridos [Nombre, Apellidos, Fecha de Nacimiento, Relacion con el Estudiante]"
    already.exists: "Usuario existente"
    min.age.validation: "Usuario debe tener 18 años o mas"
    reset.password.invalid: "No se pudo completar el reinicio de su contraseña"
    password.mismatch: "Contraseñas no coinciden"
    error.saving.profile: "Error al grabar datos del usuario"
    invalid.forgot.password.request: "Solicitud de cambio de contraseña invalida"
    cancel.reset.password.invalid: "Solicitud de cancelar reinicio de contraseña invalida"
  preenrollment:
    invalid.address.postal: "Dirección postal inválida"
    invalid.address.residential: "Dirección residencial inválida"
    already.exists: "Matricula ya existe en el sistema"
    already.submitted: "Usted ya sometio Matricula para este estudiante"




