spring:
  main:
    web-environment: false
  datasource:
    url: jdbc:oracle:thin:@auohsmaxi72-vip.oracleoutsourcing.com:11510/TMAX1O.ORACLEOUTSOURCING.COM
    username: FPALOU
    password: dev2@!8
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: de.pentaho@gmail.com
    password: d3r3ply2@!4
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    test-connection: false
