spring:
  main:
    web-environment: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: de.pentaho@gmail.com
    password: #pass
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    test-connection: true


  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    generate-ddl: false
#    database-platform: default

  # TMAX103
  #  datasource:
  #    url: jdbc:oracle:thin:@auohsmaxi72-vip.oracleoutsourcing.com:11510/TMAX1O.ORACLEOUTSOURCING.COM
  #    driver-class-name: oracle.jdbc.driver.OracleDriver
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/MEL
    username: mel
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  smaxDatasource:
    url: jdbc:oracle:thin:@auohsmaxi72-vip.oracleoutsourcing.com:11510/TMAX1O.ORACLEOUTSOURCING.COM
    username: #USER
    password: #PASS
    driver-class-name: oracle.jdbc.driver.OracleDriver
security:
  basic:
    enabled: false


