server:
  context-path: /srs-api
  port: 8081
  session:
    timeout: 900  # in seconds
    cookie:
      max-age: 900 # in seconds

spring:
  main:
    web-environment: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: de.pentaho@gmail.com
    password: d3r3ply2@!4
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    test-connection: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.type: trace

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/SRS
    username: srs
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
    platform: mysql
